SalesSystem.System.MVC/Entities/SalesRecord.cs
using SalesSystem.System.MVC.Entities.Generics;
using SalesSystem.System.MVC.Enums;

namespace SalesSystem.System.MVC.Entities
{
    public class SalesRecord : GenericEntity
    {
        public decimal Amount { get; set; }
        public SaleStatus Status { get; set; }
        public Seller Seller { get; set; }
    }
}

SalesSystem.System.MVC/Models/ViewModels/SalesRecordViewModel.cs
using SalesSystem.System.MVC.Entities;
using SalesSystem.System.MVC.Enums;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SalesSystem.System.MVC.Models.ViewModels
{
    public class SalesRecordViewModel
    {
        [Key]
        public int Id { get; set; }


        [DisplayName("Registration Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy - hh:mm:ss}")]
        public DateTime RegistrationDate { get; set; }

        
        [Required(ErrorMessage = "Required field")]
        [DataType(DataType.Currency)]
        public decimal Amount { get; set; }


        [Required(ErrorMessage = "Required field")]
        [DisplayName("State")]
        public SaleStatus Status { get; set; }


        public Seller Seller { get; set; }
    }
}

SalesSystem.System.MVC/Controllers/SalesRecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SalesSystem.System.MVC.Data.ORM;
using SalesSystem.System.MVC.Entities;
using SalesSystem.System.MVC.Models.ViewModels;

namespace SalesSystem.System.MVC.Controllers
{
    public class SalesRecordsController : Controller
    {
        private readonly SystemContext _context;
        private readonly IMapper _mapper;

        public SalesRecordsController(SystemContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: SalesRecords
        public async Task<IActionResult> Index()
        {
            var getContextData = await _context.SalesRecords.ToListAsync();
            var SalesEntityForViewModel = _mapper.Map<IEnumerable<SalesRecord>, IEnumerable<SalesRecordViewModel>>(getContextData);
            return View(SalesEntityForViewModel);
        }

        // GET: SalesRecords/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var getContextData = await _context.SalesRecords
                .FirstOrDefaultAsync(m => m.Id == id);

            var SalesEntityForViewModel = _mapper.Map<SalesRecord, SalesRecordViewModel>(getContextData);
            if (getContextData == null)
            {
                return NotFound();
            }

            return View(SalesEntityForViewModel);
        }

        // GET: SalesRecords/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Amount,Status,Id,RegistrationDate")] SalesRecordViewModel salesRecordViewModel)
        {
            if (ModelState.IsValid)
            {
                var viewModelForSalesEntity = _mapper.Map<SalesRecordViewModel, SalesRecord>(salesRecordViewModel);
                var addSales = _context.Add(viewModelForSalesEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(salesRecordViewModel);
        }

        // GET: SalesRecords/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var getContextData = await _context.SalesRecords.FirstOrDefaultAsync(prop => prop.Id == id);
            var SalesEntityForViewModel = _mapper.Map<SalesRecord, SalesRecordViewModel>(getContextData);
            if (getContextData == null)
            {
                return NotFound();
            }
            return View(SalesEntityForViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Amount,Status,Id,RegistrationDate")] SalesRecordViewModel salesRecordViewModel)
        {
            if (id != salesRecordViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var viewModelForSalesEntity = _mapper.Map<SalesRecordViewModel, SalesRecord>(salesRecordViewModel);
                    var updateSales = _context.Update(viewModelForSalesEntity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalesRecordExists(salesRecordViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(salesRecordViewModel);
        }

        // GET: SalesRecords/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var getContextData = await _context.SalesRecords
                .FirstOrDefaultAsync(m => m.Id == id);
            var salesEntityForViewModel = _mapper.Map<SalesRecord, SalesRecordViewModel>(getContextData);

            if (getContextData == null)
            {
                return NotFound();
            }

            return View(salesEntityForViewModel);
        }

        // POST: SalesRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var getContextData = await _context.SalesRecords
                .FirstOrDefaultAsync(prop => prop.Id == id);
            var deleteSales = _context.SalesRecords.Remove(getContextData);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalesRecordExists(int id)
        {
            return _context.SalesRecords.Any(e => e.Id == id);
        }
    }
}

SalesSystem.System.MVC/Views/SalesRecords/Create.cshtml
@model SalesSystem.System.MVC.Models.ViewModels.SalesRecordViewModel

@{
    ViewData["Title"] = "Register new Sale";
}

<div class="row">
    <div class="panel panel-heading">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="panel panel-body">
    <h4>SalesRecord</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <partial name="PartialViews/_sales_create_edit" />

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-success" />
                    <a asp-controller="SalesRecords" asp-action="Index" class="btn btn-warning">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SalesSystem.System.MVC/Views/SalesRecords/Delete.cshtml
@model SalesSystem.System.MVC.Models.ViewModels.SalesRecordViewModel

@{
    ViewData["Title"] = "Sales Remove";
}

<div class="row">
    <div class="panel panel-heading">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="panel panel-body">
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>SalesRecord</h4>
        <hr />

        <partial name="PartialViews/_sales_delete_details" />

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-controller="SalesRecords" asp-action="Index" class="btn btn-warning">Back</a>
        </form>
    </div>
</div>

SalesSystem.System.MVC/Views/SalesRecords/Details.cshtml
@model SalesSystem.System.MVC.Models.ViewModels.SalesRecordViewModel

@{
    ViewData["Title"] = "Sale Details";
}

<div class="row">
    <div class="panel panel-heading">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="panel panel-body">
    <div>
        <h4>SalesRecord</h4>
        <hr />

        <partial name="PartialViews/_sales_delete_details" />

    </div>
    <div>
        <a asp-controller="SalesRecords" asp-action="Edit" asp-route-id="@Model.Id"
           class="btn btn-success">Edit</a>
        <a asp-controller="SalesRecords" asp-action="Index" class="btn btn-warning">Back</a>
    </div>
</div>

SalesSystem.System.MVC/Views/SalesRecords/Edit.cshtml
@model SalesSystem.System.MVC.Models.ViewModels.SalesRecordViewModel

@{
    ViewData["Title"] = "Data Update";
}

<div class="row">
    <div class="panel panel-heading">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="panel panel-body">
    <h4>SalesRecord</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />

                <partial name="PartialViews/_sales_create_edit" />

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-success" />
                    <a asp-controller="SalesRecords" asp-action="Index" class="btn btn-warning">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SalesSystem.System.MVC/Views/SalesRecords/Index.cshtml
@model IEnumerable<SalesSystem.System.MVC.Models.ViewModels.SalesRecordViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="panel panel-heading">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="panel panel-body">
    <p>
        <a asp-action="Create" class="btn btn-secondary">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RegistrationDate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RegistrationDate)
                    </td>
                    <td>
                        <a asp-controller="SalesRecords" asp-action="Edit" asp-route-id="@item.Id"
                           class="btn btn-primary">Edit</a> 
                        <a asp-controller="SalesRecords" asp-action="Details" asp-route-id="@item.Id"
                           class="btn btn-info">Details</a> 
                        <a asp-controller="SalesRecords" asp-action="Delete" asp-route-id="@item.Id"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>