SalesSystem.System.MVC/Entities/Seller.cs
using SalesSystem.System.MVC.Entities.Generics;
using SalesSystem.System.MVC.Enums;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SalesSystem.System.MVC.Entities
{
    public class Seller : GenericEntity
    {

        public string Name { get; set; }
        public string Email { get; set; }
        public DateTime BirthDate { get; set; }
        public decimal BaseSalary { get; set; }
        public Department Department { get; set; }
        public ICollection<SalesRecord> Sales { get; set; } = new List<SalesRecord>();


        public decimal TotalSales(DateTime initial, DateTime final)
        {
            return Sales.Where(sr => sr.RegistrationDate >= initial && sr.RegistrationDate <= final)
                .Sum(sr => sr.Amount);
        }
    }
}

SalesSystem.System.MVC/Models/ViewModels/SellerViewModel.cs
using SalesSystem.System.MVC.Entities;
using SalesSystem.System.MVC.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace SalesSystem.System.MVC.Models.ViewModels
{
    public class SellerViewModel
    {
        [Key]
        public int Id { get; set; }


        [DisplayName("Registration Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy - hh:mm:ss}")]
        public DateTime RegistrationDate { get; set; }


        [Required(ErrorMessage = "Required field")]
        [MaxLength(150, ErrorMessage = "have to have at most {1} Caract")]
        [MinLength(10, ErrorMessage = "have to have at least {1}")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Required field")]
        [DisplayName("E-mail")]
        [MaxLength(120, ErrorMessage = "have to have at most {1} Caract")]
        [MinLength(10, ErrorMessage = "have to have at least {1}")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }


        [Required(ErrorMessage = "Required field")]
        [DisplayName("Birth Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime BirthDate { get; set; }


        [Required(ErrorMessage = "Required field")]
        [DisplayName("Base Salary")]
        [DataType(DataType.Currency)]
        public decimal BaseSalary { get; set; }


        [Required(ErrorMessage = "Required field")]
        public Department Department { get; set; }


        public int DepartmentId { get; set; }
        public ICollection<SalesRecord> Sales { get; set; } = new List<SalesRecord>();


        public decimal TotalSales(DateTime initial, DateTime final)
        {
            return Sales.Where(sr => sr.RegistrationDate >= initial && sr.RegistrationDate <= final).Sum(sr => sr.Amount);
        }
    }
}

SalesSystem.System.MVC/Controllers/SellersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SalesSystem.System.MVC.Data.ORM;
using SalesSystem.System.MVC.Entities;
using SalesSystem.System.MVC.Models.ViewModels;


namespace SalesSystem.System.MVC.Controllers
{
    public class SellersController : Controller
    {
        private readonly SystemContext _context;
        private readonly IMapper _mapper;

        public SellersController(SystemContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;

        }

        // GET: Sellers
        public async Task<IActionResult> Index()
        {
            var getContextData = await _context.Sellers.ToListAsync();
            var sellerEntityForViewModel = _mapper.Map<IEnumerable<Seller>, IEnumerable<SellerViewModel>>(getContextData);
            return View(sellerEntityForViewModel);
        }

        // GET: Sellers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var getContextData = await _context.Sellers
                .FirstOrDefaultAsync(m => m.Id == id);
            var sellerEntityForViewModel = _mapper.Map<Seller, SellerViewModel>(getContextData);
            if (getContextData == null)
            {
                return NotFound();
            }

            return View(sellerEntityForViewModel);
        }

        // GET: Sellers/Create
        public IActionResult Create()
        {

            return View();
        }

  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Email,BirthDate,BaseSalary,Department,DepartmentId,Id,RegistrationDate")] SellerViewModel sellerViewModel)
        {
            if (ModelState.IsValid)
            {
                var viewModelForSellerEntity = _mapper.Map<SellerViewModel, Seller>(sellerViewModel);
                var addNewSeller = _context.Add(viewModelForSellerEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sellerViewModel);
        }

        // GET: Sellers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var getContextData = await _context.Sellers.FindAsync(id);
            var sellerEntityForViewModel = _mapper.Map<Seller, SellerViewModel>(getContextData);
            if (getContextData == null)
            {
                return NotFound();
            }
            return View(sellerEntityForViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Email,BirthDate,BaseSalary,Department,DepartmentId,Id,RegistrationDate")] SellerViewModel sellerViewModel)
        {
            if (id != sellerViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var viewModelForSellerEntity = _mapper.Map<SellerViewModel, Seller>(sellerViewModel);
                    var saveEdit = _context.Update(viewModelForSellerEntity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SellerExists(sellerViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sellerViewModel);
        }

        // GET: Sellers/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var getContextData = await _context.Sellers
                .FirstOrDefaultAsync(m => m.Id == id);
            var sellerEntityForSelletEntity = _mapper.Map<Seller, SellerViewModel>(getContextData);
            if (getContextData == null)
            {
                return NotFound();
            }

            return View(sellerEntityForSelletEntity);
        }

        // POST: Sellers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var getContextData = await _context.Sellers
                .FirstOrDefaultAsync(m => m.Id == id);
            var deleteSeller = _context.Sellers.Remove(getContextData);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SellerExists(int id)
        {
            return _context.Sellers.Any(e => e.Id == id);
        }
    }
}

SalesSystem.System.MVC/Views/Sellers/Create.cshtml
@model SalesSystem.System.MVC.Models.ViewModels.SellerViewModel

@{
    ViewData["Title"] = "Register new seller";
}

<div class="row">
    <div class="panel panel-heading">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="panel panel-body">
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <partial name="PartialViews/_seller_create_edit" />

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-success" />
                    <a asp-controller="Sellers" asp-action="Index" class="btn btn-warning">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SalesSystem.System.MVC/Views/Sellers/Delete.cshtml
@model SalesSystem.System.MVC.Models.ViewModels.SellerViewModel

@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="panel panel-heading">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="panel panel-body">
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Seller</h4>
        <hr />

        <partial name="PartialViews/_seller_delete_details" />

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            <a asp-controller="Sellers" asp-action="Index" class="btn btn-warning">Back</a>
        </form>
    </div>
</div>

SalesSystem.System.MVC/Views/Sellers/Details.cshtml
@model SalesSystem.System.MVC.Models.ViewModels.SellerViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <div class="panel panel-heading">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="panel panel-body">
    <div>
        <h4>Seller</h4>
        <hr />

        <partial name="PartialViews/_seller_delete_details" />

    </div>
    <div>
        <a asp-controller="Sellers" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-success">Edit</a> 
        <a asp-controller="Sellers" asp-action="Index" class="btn btn-warning">Back</a>
    </div>
</div>

SalesSystem.System.MVC/Views/Sellers/Edit.cshtml
@model SalesSystem.System.MVC.Models.ViewModels.SellerViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="row">
    <div class="panel panel-heading">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="panel panel-body">
    <h4>Seller</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />

                <partial name="PartialViews/_seller_create_edit" />

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-success" />
                    <a asp-controller="Sellers" asp-action="Index" class="btn btn-warning">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SalesSystem.System.MVC/Views/Sellers/Index.cshtml
@model IEnumerable<SalesSystem.System.MVC.Models.ViewModels.SellerViewModel>

@{
    ViewData["Title"] = "Sellers";
}

<div class="row">
    <div class="panel panel-heading">
        <h3>@ViewData["Title"]</h3>
    </div>
</div>

<div class="panel panel-body">
    <p>
        <a asp-controller="Sellers" asp-action="Create" class="btn btn-secondary">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Department)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>                   
                    <td>
                        @Html.DisplayFor(modelItem => item.Department)
                    </td>

                    <td>
                        <a asp-controller="Sellers" asp-action="Edit" asp-route-id="@item.Id" 
                           class="btn btn-primary">Edit</a> 
                        <a asp-controller="Sellers" asp-action="Details" asp-route-id="@item.Id" 
                           class="btn btn-info">Details</a> 
                        <a asp-controller="Sellers" asp-action="Delete" asp-route-id="@item.Id" 
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>